const API_URL="https://script.google.com/macros/s/AKfycbxNjxw9fZE3-5FA1b-SjT4fl4jnjv2sOd4l3n_QY_JoteiwCV_-5sIDtLq2ckWFRGVV/exec";
const fallbackLinks=[{Category:"Variance",Name:"Variance Sheet 1",Description:"Google Sheet quick access.",URL:"https://docs.google.com/spreadsheets/d/17iIrGTk6PUQ9FfOkaDEN3vix_AskTMTxMcwgigWiOlM/edit?usp=sharing",Icon:"clipboard-data",Status:"Active"},{Category:"Variance",Name:"Variance Sheet 2",Description:"Google Sheet quick access.",URL:"https://docs.google.com/spreadsheets/d/1jsy5ZEWTiK0_S1dx0an6Ib3YphmCQ1cHw06H13pt7Xg/edit?usp=sharing",Icon:"table",Status:"Active"},{Category:"Variance",Name:"Variance Sheet 3",Description:"Google Sheet quick access.",URL:"https://docs.google.com/spreadsheets/d/1aXv_-uXP_qiMLXZzpDy_2bvgJV8533QuvUfQFeTUnvI/edit?usp=sharing",Icon:"bar-chart-line",Status:"Active"}];
let allLinks=[],currentCategory="all";const cardsContainer=document.getElementById("cardsContainer"),categoryMenu=document.getElementById("categoryMenu"),searchInput=document.getElementById("searchInput"),totalLinks=document.getElementById("totalLinks"),activeLinks=document.getElementById("activeLinks"),totalCategories=document.getElementById("totalCategories"),lastLoaded=document.getElementById("lastLoaded"),statusMessage=document.getElementById("statusMessage"),refreshBtn=document.getElementById("refreshBtn"),darkModeBtn=document.getElementById("darkModeBtn");
document.addEventListener("DOMContentLoaded",init);
function init(){if(localStorage.getItem("darkMode")==="yes")document.body.classList.add("dark");searchInput.addEventListener("input",renderPortal);refreshBtn.addEventListener("click",loadData);darkModeBtn.addEventListener("click",toggleDarkMode);document.querySelector('[data-filter="all"]').addEventListener("click",()=>{currentCategory="all";setActiveMenu("all");renderPortal()});loadData()}
async function loadData(){showLoading();try{const response=await fetch(API_URL,{method:"GET"});if(!response.ok)throw new Error("API failed");const data=await response.json();if(!Array.isArray(data))throw new Error("API did not return array");allLinks=data.map(normalizeRow).filter(item=>item.Name&&item.URL);if(allLinks.length===0){allLinks=fallbackLinks;showStatus("Walang valid rows sa Google Sheet. Fallback links muna ang ipinapakita.")}else statusMessage.innerHTML="";updateLastLoaded();buildCategoryMenu();renderPortal()}catch(error){console.error(error);allLinks=fallbackLinks;showStatus("Hindi ma-load ang Apps Script API. Fallback links muna ang ipinapakita. Check deployment/access ng Apps Script.");updateLastLoaded();buildCategoryMenu();renderPortal()}}
function normalizeRow(row){return{Category:String(row.Category||"Variance").trim(),Name:String(row.Name||"").trim(),Description:String(row.Description||"Google Sheet quick access.").trim(),URL:String(row.URL||"").trim(),Icon:String(row.Icon||"clipboard-data").trim(),Status:String(row.Status||"Active").trim()}}
function renderPortal(){const keyword=searchInput.value.trim().toLowerCase();const active=allLinks.filter(item=>String(item.Status||"Active").toLowerCase()!=="inactive");let filtered=active;if(currentCategory!=="all")filtered=filtered.filter(item=>item.Category===currentCategory);if(keyword)filtered=filtered.filter(item=>item.Name.toLowerCase().includes(keyword)||item.Description.toLowerCase().includes(keyword)||item.Category.toLowerCase().includes(keyword));updateStats(active);renderCards(filtered)}
function renderCards(items){cardsContainer.innerHTML="";if(items.length===0){cardsContainer.innerHTML='<div class="empty-box"><i class="bi bi-search fs-2"></i><p class="mt-2 mb-0">No sheet found.</p></div>';return}const grouped=groupByCategory(items);Object.keys(grouped).forEach(category=>{const block=document.createElement("div");block.className="category-block";block.innerHTML=`<h4><i class="bi bi-folder2-open me-2"></i>${escapeHtml(category)}</h4><div class="cards-grid"></div>`;const grid=block.querySelector(".cards-grid");grouped[category].forEach(item=>{const card=document.createElement("div");card.className="portal-card";card.innerHTML=`<div class="card-top"><div class="icon-box"><i class="bi bi-${escapeHtml(item.Icon)}"></i></div><span class="badge text-bg-success rounded-pill">${escapeHtml(item.Status)}</span></div><h5>${escapeHtml(item.Name)}</h5><p>${escapeHtml(item.Description)}</p><a class="btn btn-primary w-100 btn-open" target="_blank" rel="noopener" href="${escapeHtml(item.URL)}"><i class="bi bi-box-arrow-up-right me-1"></i> Open Sheet</a>`;grid.appendChild(card)});cardsContainer.appendChild(block)})}
function buildCategoryMenu(){const categories=[...new Set(allLinks.filter(item=>String(item.Status||"Active").toLowerCase()!=="inactive").map(item=>item.Category||"Variance"))].sort();categoryMenu.innerHTML="";categories.forEach(category=>{const button=document.createElement("button");button.className="nav-link";button.dataset.filter=category;button.innerHTML=`<i class="bi bi-folder"></i> ${escapeHtml(category)}`;button.addEventListener("click",()=>{currentCategory=category;setActiveMenu(category);renderPortal()});categoryMenu.appendChild(button)})}
function setActiveMenu(filter){document.querySelectorAll(".nav-link").forEach(btn=>btn.classList.toggle("active",btn.dataset.filter===filter))}
function updateStats(active){const categories=new Set(active.map(item=>item.Category||"Variance"));totalLinks.textContent=allLinks.length;activeLinks.textContent=active.length;totalCategories.textContent=categories.size}
function updateLastLoaded(){lastLoaded.textContent=new Date().toLocaleTimeString("en-PH",{hour:"2-digit",minute:"2-digit"})}
function showLoading(){cardsContainer.innerHTML='<div class="empty-box"><div class="spinner-border text-primary mb-3" role="status"></div><p class="mb-0">Loading Google Sheet database...</p></div>'}
function showStatus(message){statusMessage.innerHTML=`<div class="alert-box"><strong>Notice:</strong> ${escapeHtml(message)}</div>`}
function groupByCategory(items){return items.reduce((groups,item)=>{const category=item.Category||"Variance";if(!groups[category])groups[category]=[];groups[category].push(item);return groups},{})}
function toggleDarkMode(){document.body.classList.toggle("dark");localStorage.setItem("darkMode",document.body.classList.contains("dark")?"yes":"no")}
function escapeHtml(text){return String(text).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
